name: AmplificationBackpack
version: 1.0.0
main: amplificationBackpack.AmplificationBackpack
depend: [ItemNBTAPI,LangUtils]

commands:
  amplificationbackpack:
    aliases: ab
  sortbackpack:
    aliases: sb